version: "3"

services:
  ai-debug:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./.env:/app/.env
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - ai-debug-network

networks:
  ai-debug-network:
    driver: bridge
